# Generated by Django 5.0.4 on 2024-05-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='patent',
            field=models.CharField(default=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tries_left',
            field=models.IntegerField(default=5, verbose_name='Intentos restantes'),
        ),
    ]
