# Generated by Django 5.0.4 on 2024-05-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_user_tries_left_alter_user_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="patent",
            field=models.CharField(default=False, max_length=20, unique=True),
        ),
    ]
