# Generated by Django 5.0.4 on 2024-05-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_user_id_recuperation_alter_user_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_bloqued',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='user',
            name='ID_recuperation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id de recuperacion'),
        ),
    ]
