# Generated by Django 5.0.4 on 2024-05-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_user_id_recuperation_alter_user_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type_user",
            field=models.IntegerField(
                choices=[
                    (0, "Usuario normal"),
                    (1, "Usuario con permisos para publicar"),
                    (2, "Administrador"),
                ],
                verbose_name="Tipo de usuario",
            ),
        ),
    ]
