# Generated by Django 5.0.4 on 2024-05-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_is_bloqued_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type_ship',
            new_name='ship_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ID_recuperation',
            new_name='recovery_ID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type_user',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='request_verification',
            new_name='verification_requested',
        ),
    ]
