# Generated by Django 5.0.4 on 2024-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_type_ship_post_ship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tries_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Intentos restantes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
    ]
